api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/config/api_platform']
    collection:
        pagination:
            items_per_page: 10
            client_items_per_page: true
