<?php

namespace App\Repository;

use ApiPlatform\Core\Annotation\ApiResource;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
}
